\Sexpr{set_parent('src/master.Rnw')}
\Sexpr{opts_knit$set(self.contained=FALSE)}

\graphicspath{{./anxiety_symptoms/}}

<<>>=
# print(getwd())
@

<<>>=
source('src/anxiety_symptoms/anxiety_simptoms_setup.R')
@

\begin{center}
\Huge{\textbf{Síntomas de Ansiedad}}
\end{center}

\Large La puntación de síntomas de ansiedad tiene un rango de 10 (mejor) a 90 (peor). Una
puntación de 50 es el promedio.\\

Su puntuación de síntomas de ansiedad fue \Sexpr{config_pt_anxiety}.

\newpage
