\Sexpr{set_parent('src/master.Rnw')}
\Sexpr{opts_knit$set(self.contained=FALSE)}

\graphicspath{{./depression_symptoms_a/}}

<<>>=
# print(getwd())
@

<<>>=
source('src/depression_symptoms_a/depression_symptoms_a_setup.R')
@

\begin{center}
\Huge{Depression Symptoms A}
\end{center}

\Large{
Your level of depression symptoms was \Sexpr{pt_stat}.\\

The level of depression symptoms for
\Sexpr{tolower(get_men_women(config_pt_sex))}
in your age group was \Sexpr{other_stat}.

\newpage
