<<echo=FALSE, results='hide', warning=FALSE, message=FALSE>>=
library(knitr)
library(ggplot2)
library(reshape2)
library(png)
library(grid)
library(gridExtra)
library(stringi)
# library(extrafont)

opts_chunk$set(cache = FALSE, dpi = 300)
opts_chunk$set(comment = "", tidy = TRUE, size = "small")
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
opts_chunk$set(fig.width = 10, fig.height = 6)
opts_knit$set(root.dir = normalizePath('../'))
# opts_chunk$set(fig.path='Figs-English/')
@

<<echo=FALSE, results='hide', warning=FALSE, message=FALSE>>=
# font_import()
# loadfonts()

# comment out below 3 lines if running batch
data_config_pt_language <- "english"
pt_english <- 'Sample1' # person's name
pt_id <- 'Sample1' # person's ID

source('src/helper-00-pt-config.R')
source('src/helper.R')
@

\documentclass[12pt]{article}
\usepackage[landscape]{geometry}
\usepackage{fullpage}
\setlength{\parindent}{0pt}
\usepackage{svg}
\usepackage[justification=centering]{caption}
\usepackage{float}
\usepackage{units}
\usepackage{graphicx}
\usepackage{multirow}
\usepackage{fancyhdr}
\usepackage{array}
\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{R}[1]{>{\raggedleft\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}

\renewcommand{\familydefault}{\sfdefault}

\pagestyle{fancy}
\fancyhf{} % sets both header and footer to nothing
\renewcommand{\headrulewidth}{0pt}
% your new footer definitions here
% \lhead{}
% \chead{}
% \rhead{\Sexpr{data_config_pt_name}}
% \lfoot{}
% \cfoot{}
% \rfoot{}

\pagenumbering{gobble}

\begin{document}

<<>>=
t(as.matrix(data_pt_selected))

print(getwd())
print(data_config_pt_name)
@

\newpage

<<body_mass_index, child="body_mass_index/english_body_mass_index.Rnw">>=
@

<<waist_measurement, child="waist_measurement/english_waist_measurement.Rnw">>=
@

<<days_feeling_depressed, child="days_feeling_depressed/english_days_feeling_depressed.Rnw">>=
@

<<days_feeling_anxious, child="days_feeling_anxious/english_days_feeling_anxious.Rnw">>=
@

<<fruit_servings_per_day, child="fruit_servings_per_day/english_fruit_servings_per_day.Rnw">>=
@

<<vegetable_servings_per_day, child="vegetable_servings_per_day/english_vegetable_servings_per_day.Rnw">>=
@

<<minutes_vigorous_exercise, child="minutes_vigorous_exercise/english_minutes_vigorous_exercise.Rnw">>=
@

<<minutes_moderate_exercise, child="minutes_moderate_exercise/english_minutes_moderate_exercise.Rnw">>=
@

<<composite_beverage_servings, child="composite_beverage_servings/english_composite_beverage_servings.Rnw">>=
@

<<composite_30_day_measures, child="composite_30_day_measures/english_composite_30_day_measures.Rnw">>=
@

<<recommended_physical_activity, child="recommended_physical_activity/english_recommended_physical_activity.Rnw">>=
@

<<beverage_recommendations, child="beverage_recommendations/english_beverage_recommendations.Rnw">>=
@

<<depression_symptoms_a, child="depression_symptoms_a/english_depression_symptoms_a.Rnw">>=
@

<<prolonged_stress, child="prolonged_stress/english_prolonged_stress.Rnw">>=
@

<<anxiety_symptoms, child="anxiety_symptoms/english_anxiety_symptoms.Rnw">>=
@

<<depression_symptoms_b, child="depression_symptoms_b/english_depression_symptoms_b.Rnw">>=
@

<<overall_health, child="overall_health/english_overall_health.Rnw">>=
@

<<loss_of_energy, child="loss_of_energy/english_loss_of_energy.Rnw">>=
@

<<risks_of_high_blood_pressure, child="risks_of_high_blood_pressure/english_risks_of_high_blood_pressure.Rnw">>=
@

<<risks_of_excess_weight, child="risks_of_excess_weight/english_risks_of_excess_weight.Rnw">>=
@

<<health_comparted_to_ideal_cloverleaf, child="health_compared_to_ideal_cloverleaf/english_health_compared_to_ideal_cloverleaf.Rnw">>=
@

<<blood_pressure_a_and_b, child="blood_pressure_a_and_b/english_blood_pressure_a_and_b.Rnw">>=
@

\end{document}
